name: Selenium Scraping

on:
  schedule:
    - cron: '0 0 * * *'  # Define a cron schedule (executará diariamente à meia-noite)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Se houver algum arquivo requirements.txt com as dependências necessárias

    - name: Run Selenium script
      run: python scraper.py

